import type { Metadata } from 'next'
import { DM_Serif_Display } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from './components/Navbar'
import Footer from './components/Footer'
import { cn } from '@/lib/utils'
import { ClerkProvider } from '@clerk/nextjs'

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
})

const dmSerif = DM_Serif_Display({
  variable: '--font-dm-serif',
  subsets: ['latin'],
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={cn(poppins.variable, dmSerif.variable, 'antialiased')}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
    </ClerkProvider>
  )
}
